---

- name: Install configsnap
  yum:
    name: configsnap
    state: latest

- name: create configsnap pre apply script
  copy:
    content: "/usr/sbin/configsnap --silent -d /root -t auter-configsnap-$(date +%Y-%m-%d) -p pre"
    dest: /etc/auter/pre-apply.d/01-configsnap-pre
    mode: 0755

- name: create configsnap post apply script
  copy:
    src: 50-configsnap-post-apply
    dest: /etc/auter/post-apply.d/50-configsnap-post-apply
    mode: 0755

- name: create configsnap pre reboot script
  copy:
    src: 98-configsnap-pre-reboot
    dest: /etc/auter/pre-reboot.d/98-configsnap-pre-reboot
    mode: 0755

- name: create configsnap post reboot script
  copy:
    src: 99-configsnap-post-reboot
    dest: /etc/auter/post-reboot.d/99-configsnap-post-reboot
    mode: 0755

...
