---
- hosts: all
  become: True
  vars:
    csv_file: ./schedule_list.csv
    cron_file: auter
    days_later: "{{ lookup('csvfile', inventory_hostname + ' file=' + csv_file + ' col=1 delimiter=,') }}"

  tasks:
    - debug:
        msg: "{{ days_later }}"

    - name: Pre-check if server has configuration set in CSV file
      become: False
      changed_when: False
      local_action: command grep ^{{ inventory_hostname }}, {{ csv_file }}

    - name: Lookup schedule hour from the CSV file
      set_fact:
        hour: "{{ lookup('csvfile', inventory_hostname + ' file=' + csv_file + ' col=2 delimiter=,').split(':')[0] }}"

    - name: Check if hour is an integer
      local_action: command python -c "int('{{ hour }}')"
      register: hour_int_check
      become: False
      failed_when: False
      changed_when: False

    - name: Fail if server's schedule hour is invalid
      fail:
        msg: schedule hour for {{ inventory_hostname }} is invalid
      when:
        hour_int_check.rc != 0 or hour|int < 0 or hour|int > 23

    - name: Lookup schedule minute from the CSV file
      set_fact:
        minute: "{{ lookup('csvfile', inventory_hostname + ' file=' + csv_file + ' col=2 delimiter=,').split(':')[1] }}"

    - name: Check if minute is an integer
      local_action: command python -c "int('{{ minute }}')"
      register: minute_int_check
      become: False
      failed_when: False
      changed_when: False

    - name: Fail if server's schedule minute is invalid
      fail:
        msg: schedule minute for {{ inventory_hostname }} is invalid
      when:
        minute_int_check.rc != 0 or minute|int < 0 or minute|int > 59

# This creates a job that will run '/usr/bin/auter --apply'  {{ daysLater }} after the second tuesday of the month
    - name: Add cron jobs as defined by the server's schedule group
      cron: 
        name: "Patch days after:"
        cron_file: "{{ cron_file }}"
        minute: "{{ minute }}"
        hour: "{{ hour }}"
        user: "root"
        job: "[[ $(date +%D) == $(date --date $(date +%Y-%m)-$(LC_ALL=C cal | cut -b 7-8 | xargs | awk '{print $4}')+{{ days_later }}days +%D) ]] && /usr/bin/auter --apply"
...
