---
- hosts: all
  gather_facts: False

  vars_prompt:
    name: reportName
    prompt: Report name
    default: default
    private: no

  tasks:
    - name: Generate Date
      local_action: 'shell date +%d-%m-%y'
      delegate_to: localhost
      run_once: true
      become: False
      register: ReportDate

    - set_fact:
        csv_file: ./auter-audit-{{ reportName }}-{{ ReportDate.stdout }}.csv

    - delegate_to: localhost
      run_once: true
      debug:
        var: csv_file


    - name: Run the audit script
      script: ./auter-audit.sh -c
      become: True
      register: auter_audit_output

#    - debug:
#        msg: "{{ auter_audit_output.stdout_lines[4] }}"

    - name: Write header
      delegate_to: localhost
      run_once: true
      local_action: lineinfile
                    create=yes
                    state=present
                    dest={{ csv_file }}
                    line='Hostname,Version,Status,LastUpdate'

    - name: Append output to CSV file
      local_action: lineinfile
                    create=no
                    state=present
                    dest={{ csv_file }}
                    line={{ auter_audit_output.stdout_lines[4] }}
...

